services:
  accounts:
    build: ./accounts
    image: nguyenductiep/accounts
    container_name: account-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ndtiepbank-net
  loans:
    build: ./loans
    image: nguyenductiep/loans
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ndtiepbank-net
  cards:
    build: ./cards
    image: nguyenductiep/cards
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ndtiepbank-net
networks:
  ndtiepbank-net:
    driver: "bridge"
