spring:
  config:
    activate:
      on-profile: "dev"

build:
  version: "1.0"

accounts:
  message: "Welcome to NdtiepBank accounts related dev APIs "
  contactDetails:
    name: "Tiep Nguyen - Web Developer"
    email: "ndtiep@lgcns.com"
  onCallSupport:
    - 123333312312
    - 12312331123