spring:
  application:
    name: configserver
  profiles:
    active: git
  #    active: native
  cloud:
    config:
      server:
#       native:
#         search-locations: "file:///Users/projects/configserver/config"
#         search-locations: "classpath:/config"
        git:
          uri: "https://github.com/tiepnd/ndtiepbank-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8071

